name: "HAOS Kiosk Display"
description: >
  Start X server and browser on local HAOS server and display dashboards in kiosk mode (Jeff Kosowsky)
version: "0.9.6"
slug: "haoskiosk"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
host_network: true
host_dbus: true
init: false

devices:
  - /dev/dri
  - /dev/fb0
  - /dev/fb1
  - /dev/input/event0
  - /dev/input/event1

privileged:
  - SYS_ADMIN

security_opt:
  - apparmor:unconfined

options:
  ha_url: "http://localhost:8123"
  ha_dashboard: ""
  login_delay: 1.0 
  hdmi_port: 0
  screen_timeout: 600
  browser_refresh: 600
  zoom_level: 100

schema:
  ha_username: str
  ha_password: password
  ha_url: str
  ha_dashboard: str
  login_delay: float(0,)
  hdmi_port: int(0,1)
  screen_timeout: int(0,)
  browser_refresh: int(0,)
  zoom_level: int(0,)

environment:
  DISPLAY: ":0"
